// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0_-PmlcGq7BFLPLfoutRpkjRqqcHb3KA',
    appId: '1:817940784403:android:06be04df2afbd2cdc9e6e6',
    messagingSenderId: '817940784403',
    projectId: 'travel-app-beb08',
    storageBucket: 'travel-app-beb08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XxBKGYL92sob_Y_pOA55sOWwVGLPDT0',
    appId: '1:817940784403:ios:72d14db80f683ca4c9e6e6',
    messagingSenderId: '817940784403',
    projectId: 'travel-app-beb08',
    storageBucket: 'travel-app-beb08.appspot.com',
    androidClientId: '817940784403-0osppseplo06466dd12pidh10gil207c.apps.googleusercontent.com',
    iosClientId: '817940784403-9cbq1bvm1gsevcioe0frfs3kktetca8c.apps.googleusercontent.com',
    iosBundleId: 'com.travelapp.travelApp',
  );
}
